//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.BLL.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Task.BLL.Resourses.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description cannot be over 300 charecters.
        /// </summary>
        internal static string DescriptionIsGreaterThan {
            get {
                return ResourceManager.GetString("DescriptionIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cannot be null.
        /// </summary>
        internal static string IdIsNull {
            get {
                return ResourceManager.GetString("IdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cannot be less than 1.
        /// </summary>
        internal static string IdLessThan {
            get {
                return ResourceManager.GetString("IdLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be empty.
        /// </summary>
        internal static string NameIsEmpty {
            get {
                return ResourceManager.GetString("NameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name canot be over than 20.
        /// </summary>
        internal static string NameIsGreaterThan {
            get {
                return ResourceManager.GetString("NameIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be less than 1.
        /// </summary>
        internal static string NameIsLessThan {
            get {
                return ResourceManager.GetString("NameIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality cannot be empty.
        /// </summary>
        internal static string SpecialityIsEmpty {
            get {
                return ResourceManager.GetString("SpecialityIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality cannot be over than 50.
        /// </summary>
        internal static string SpecialityIsGreaterThan {
            get {
                return ResourceManager.GetString("SpecialityIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality cannot be less than 4.
        /// </summary>
        internal static string SpecialityIsLessThan {
            get {
                return ResourceManager.GetString("SpecialityIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student id cannot be null.
        /// </summary>
        internal static string StudentIdIsNull {
            get {
                return ResourceManager.GetString("StudentIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student id cannot be less than 1.
        /// </summary>
        internal static string StudentIdLessThan {
            get {
                return ResourceManager.GetString("StudentIdLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname cannot be empty.
        /// </summary>
        internal static string SurnameIsEmpty {
            get {
                return ResourceManager.GetString("SurnameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname canot be over than 30.
        /// </summary>
        internal static string SurnameIsGreaterThan {
            get {
                return ResourceManager.GetString("SurnameIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname cannot be less than 1.
        /// </summary>
        internal static string SurnameIsLessThan {
            get {
                return ResourceManager.GetString("SurnameIsLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher id cannot be null.
        /// </summary>
        internal static string TeacherIdIsNull {
            get {
                return ResourceManager.GetString("TeacherIdIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher id cannot be less than 1.
        /// </summary>
        internal static string TeacherIdLessThan {
            get {
                return ResourceManager.GetString("TeacherIdLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty.
        /// </summary>
        internal static string TitleIsEmpty {
            get {
                return ResourceManager.GetString("TitleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be over 20 charecters.
        /// </summary>
        internal static string TitleIsGreaterThan {
            get {
                return ResourceManager.GetString("TitleIsGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be less than 1 charecter.
        /// </summary>
        internal static string TitleIsLessThan {
            get {
                return ResourceManager.GetString("TitleIsLessThan", resourceCulture);
            }
        }
    }
}
